name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Deploy to Tomcat
      env:
        TOMCAT_USER: ${{ secrets.TOMCAT_USER }}
        TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
        TOMCAT_HOST: ${{ secrets.TOMCAT_HOST }}
        TOMCAT_PORT: ${{ secrets.TOMCAT_PORT }}
      run: |
        curl -u $TOMCAT_USER:$TOMCAT_PASSWORD \
             -T target/addressbook-2.0.war \
             "http://$TOMCAT_HOST:$TOMCAT_PORT/manager/text/deploy?path=/yourapp&update=true"
